// Code generated by bpf2go; DO NOT EDIT.

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadTest returns the embedded CollectionSpec for Test.
func LoadTest() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TestBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Test: %w", err)
	}

	return spec, err
}

// LoadTestObjects loads Test and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*TestObjects
//	*TestPrograms
//	*TestMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadTestObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadTest()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// TestSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestSpecs struct {
	TestProgramSpecs
	TestMapSpecs
}

// TestSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestProgramSpecs struct {
	BpfProg1 *ebpf.ProgramSpec `ebpf:"bpf_prog1"`
}

// TestMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type TestMapSpecs struct {
}

// TestObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestObjects struct {
	TestPrograms
	TestMaps
}

func (o *TestObjects) Close() error {
	return _TestClose(
		&o.TestPrograms,
		&o.TestMaps,
	)
}

// TestMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestMaps struct {
}

func (m *TestMaps) Close() error {
	return _TestClose()
}

// TestPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadTestObjects or ebpf.CollectionSpec.LoadAndAssign.
type TestPrograms struct {
	BpfProg1 *ebpf.Program `ebpf:"bpf_prog1"`
}

func (p *TestPrograms) Close() error {
	return _TestClose(
		p.BpfProg1,
	)
}

func _TestClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed test_bpf.o
var _TestBytes []byte
